### ISSUE TITLE
The role of sampling_weights.

### ISSUE THREAD

**Issue by Alxead** [eloialonso/iris#10]
Hi, what's the function of `sampling_weights` in trainer.yaml ? 
[  sampling_weights: [0.125, 0.125, 0.25, 0.5]](https://github.com/eloialonso/iris/blob/42bbabee7cdeeed6e974b2198c1fec394d87a4eb/config/trainer.yaml#L56)

It seems that `weights=1` are always used for all the episodes in function `_sample_episodes_segments` in `dataset.py`.

**Comment by eloialonso** [comment]
Hi, this is a simple way to sample recent experience more often. 

In `_sample_episodes_segments`, we use equal weights (no effect) if `weights` is None or if there isn't enough episodes in the dataset. 

Otherwise, the nth weight corresponds to the probability of sampling an episode in the nth chunk of the dataset in chronological order. 

For instance, with `weights = [0.125, 0.125, 0.25, 0.5]`, there is a 0.5 probability that an episode from the most recent quarter of the dataset will be sampled.

**Comment by Alxead** [comment]
I understand, thank you!

**Comment by eloialonso** [comment]
Sorry for the misunderstanding, this was indeed a bug (reported again in #18). We removed this feature as it was not used during our experiments.
